name: Renommer les images PNG

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  rename:
    name: Renommer les fichiers images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Renommer les fichiers PNG
        run: |
          find Images/ -type f -iname "*.png" | while read file; do
            dir=$(dirname "$file")
            base=$(basename "$file")
            name="${base%.*}"
            ext="${base##*.}"
            if [[ "${name,,}" == *down ]]; then
              newname="${name} *2.${ext}"
            else
              newname="${name}u.${ext}"
            fi
            target="$dir/$newname"
            if [ -e "$target" ]; then
              echo "Ignoré : $file (cible $newname existe déjà)"
            else
              echo "Renommé : $file → $newname"
              git mv "$file" "$target"
            fi
          done

      - name: Créer une Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Renommage automatique des fichiers PNG"
          title: "Renommage automatique des fichiers images PNG"
          body: "Ce PR renomme les fichiers .png selon les règles spécifiées."
          
